{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "s3-purger-loki.fullname" . }}-allow
spec:
  podSelector:
    matchLabels:
      app: {{ include "s3-purger-loki.fullname" . }}
      release: {{ include "s3-purger-loki.fullname" . }}
  egress:
    - ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    - ports:
        - protocol: TCP
          port: 9090
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: kube-prometheus-stack-prometheus
              app.kubernetes.io/name: prometheus
  policyTypes:
    - Egress
{{ end }}
